#!/bin/bash

cd IEEE1451SmartSensorFederation/IEEE1451SmartSensorFederation_generated/
mvn clean install

cd IEEE1451SmartSensorFederation/IEEE1451SmartSensorFederation_deployment/
mvn clean install

cd IEEE1451SmartSensorSimulator/IEEE1451SmartSensorFederation_generated/
mvn clean install

cd IEEE1451SmartSensorSimulator/IEEE1451SmartSensorFederation_deployment/
mvn clean install

cd IEEE1451SmartSensorTester/IEEE1451SmartSensorFederation_generated/
mvn clean install

cd IEEE1451SmartSensorTester/IEEE1451SmartSensorFederation_deployment
mvn clean install

